name: Python API CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 main.py

  delivery:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t yourdockerhubusername/python-api-devops .
      
      - name: Push Docker image
        run: |
          docker tag ferremanendonckx/python-api-devops:latest ferremanendonckx/python-api-devops:latest
          docker push ferremanendonckx/python-api-devops:latest

